# Generated by Django 4.2.1 on 2023-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
