# Generated by Django 4.2.1 on 2023-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccounts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
