# Generated by Django 4.2.1 on 2023-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='uid',
            field=models.CharField(default='U_270', max_length=255, primary_key=True, serialize=False),
        ),
    ]
