# Generated by Django 4.2.1 on 2023-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='uid',
            field=models.CharField(default='U_111', max_length=255, primary_key=True, serialize=False),
        ),
    ]
