# Generated by Django 4.2.1 on 2023-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='Country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='State',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
