# Generated by Django 4.2.1 on 2023-06-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccounts_city_alter_useraccounts_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounts',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
