# Generated by Django 4.2.1 on 2023-06-22 03:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccounts_name_alter_useraccounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='uid',
            field=models.CharField(default=accounts.models.random_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
