# Generated by Django 4.2.1 on 2023-06-27 10:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='Adhar_Card',
            field=models.ImageField(null=True, upload_to=accounts.models.UserAccounts.FileName),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='license_id',
            field=models.ImageField(null=True, upload_to=accounts.models.UserAccounts.FileName),
        ),
    ]
