# Generated by Django 4.2.1 on 2023-06-13 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccounts_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
