# Generated by Django 4.2.1 on 2023-06-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccounts_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='uid',
        ),
    ]
