# Generated by Django 4.2.1 on 2023-06-22 03:37

import Bike_Info.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Info',
            fields=[
                ('b_id', models.CharField(default=Bike_Info.models.random_bike, max_length=255, primary_key=True, serialize=False)),
                ('Electrical', models.BooleanField(default=False)),
                ('KM', models.BigIntegerField()),
                ('Condition', models.BooleanField(default=True)),
                ('Pic_after', models.ImageField(null=True, upload_to=Bike_Info.models.Bike_Info.FileName)),
                ('Pic_before', models.ImageField(null=True, upload_to=Bike_Info.models.Bike_Info.FileName)),
                ('Estimated_Amount', models.BigIntegerField(null=True)),
                ('Exact_Amount', models.BigIntegerField(null=True)),
                ('Payed', models.BooleanField(default=False)),
                ('Mode_of_Payment', models.CharField(max_length=255, null=True)),
                ('Time_Taken', models.TimeField(blank=True, null=True)),
                ('Time_Return', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Bike_Info',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bike_Info.bike_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
    ]
