# Generated by Django 4.2.1 on 2023-06-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Info', '0002_bike_info_is_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike_info',
            name='Time_Return',
        ),
        migrations.RemoveField(
            model_name='bike_info',
            name='Time_Taken',
        ),
    ]
