# Generated by Django 4.2.1 on 2023-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Info', '0003_remove_bike_info_time_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_info',
            name='license_plate',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
