# Generated by Django 4.2.1 on 2023-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Info', '0004_bike_info_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_info',
            name='license_plate',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
