# Generated by Django 4.2.1 on 2023-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike_Info', '0005_alter_bike_info_license_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike_info',
            old_name='KM',
            new_name='KM_Later',
        ),
        migrations.AddField(
            model_name='bike_info',
            name='KM_Previous',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
